### ISSUE TITLE
improve performance of yt-dlp by using `--use-extractors` option

### ISSUE THREAD

**Issue by dasl-** [dasl-/pifi#34]
See discussion here https://github.com/yt-dlp/yt-dlp/pull/3234

https://github.com/yt-dlp/yt-dlp/pull/3234#issuecomment-1225128666

**Comment by dasl-** [comment]
fyi @jordanlewis

**Comment by jordanlewis** [comment]
🎉

**Comment by dasl-** [comment]
See commit message for more details https://github.com/dasl-/pifi/commit/959d383040f5fd5bafc134a281bfadc344852c7c
