### ISSUE TITLE
reduce the time it takes to start playing a video

### ISSUE THREAD

**Issue by dasl-** [dasl-/pifi#9]
~~We should be able to parallelize our two youtube-dl invocations in a similar manner to how we did here: https://github.com/dasl-/piwall2/commit/f77c69c07e03a831408b6c94d3241e95c3a52002~~ addressed via https://github.com/dasl-/pifi/commit/a6f6668b28522d1d1f56d6bb69718f366909d202

It would be nice if we could speed up the execution of yt-dlp. 
* See https://github.com/yt-dlp/yt-dlp/pull/3234
* See https://github.com/yt-dlp/yt-dlp/pull/860

**Comment by jordanlewis** [comment]
https://github.com/yt-dlp/yt-dlp/pull/3234 should help with the startup time. On my pi, 9 seconds is spent simply initializing extractors, none of which we'll use except for the youtube one. Another slow thing is checking the version of `ffmpeg`, which takes about a second, but I didn't see a simple way to avoid doing that.

**Comment by dasl-** [comment]
wow 9 seconds?? Out of how many seconds total?

**Comment by dasl-** [comment]
>Another slow thing is checking the version of ffmpeg, which takes about a second, but I didn't see a simple way to avoid doing that.

Can you link to where this occurs in the code?

**Comment by jordanlewis** [comment]
![image](https://user-images.githubusercontent.com/43821/160493111-01c9e605-4a1c-4222-9992-6f916fdeb5c5.png)

**Comment by jordanlewis** [comment]
Er, I think it was more like 5 seconds, but still a significant improvement to remove that stuff.

**Comment by dasl-** [comment]
addressed via https://github.com/dasl-/pifi/issues/34
